### ISSUE TITLE
True residual gradient norm value?

### ISSUE THREAD

**Issue by elichienxD** [facebookresearch/certified-removal#1]
Hi @cg563,

Thanks for making your code public. I'm very interested in your work and I would like to reproduce the experiment. However, I have a problem with reproducing Figure 2. I wonder how do you compute the true residual gradient norm value (black dash line)?

I've tried to use the function lr_grad as follows
![image](https://user-images.githubusercontent.com/46387845/166131928-b808cd17-f92e-4bbb-9461-c7f9c829d846.png)

However, the resulting value is much larger than the data dependent bound and those reported in the Figure 2 of your paper. For example, when I use your default setting to run the code on MNIST:

```
python test_removal.py --data-dir ./ --verbose --extractor none --dataset MNIST --train-mode binary --std 10 --lam 1e-3 --num-steps 100
```

I get the following result
![image](https://user-images.githubusercontent.com/46387845/166131978-ae6d7c26-91ee-4d48-ae97-c3b9e239c1d5.png)

where the True Grad Norm is computed as described above. Please let me know if I misunderstand something and how to reproduce your Figure 2 with the true true residual gradient norm value (black dash line).

Thanks,
Eli

**Comment by cg563** [comment]
Hi, sorry for the late response!

Since the model is trained with objective perturbation, the true gradient is not simply `lr_grad`, but rather:
`Accum_True_RGN = (lr_grad(w_approx, X_rem, y_rem, args.lam) + b).norm()`
where `b` is the perturbation vector. Doing this should allow you to reproduce Figure 2.

Hope this helps, and let me know if you have further questions.

**Comment by elichienxD** [comment]
Hi @cg563 ,

Thanks for the help! Now the results seem reasonable :)

Best,
Eli
